services:
  - type: web
    name: uniscores
    env: python
    buildCommand: "./manage.py collectstatic --noinput"
    startCommand: "gunicorn UniScores.wsgi:application --bind 0.0.0.0:8000"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: UniScores.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: ALLOWED_HOSTS
        value: uniaz.onrender.com,www.uniaz.info,uniaz.info
